# Site settings
title: Thomas Schühly
description: My Portfolio
baseurl: "/"
url: "tschuehly.github.io"
#baseurl: "/docs"
#url: "127.0.0.1:4000" #

# User settings
username: Thomas Schühly
email: thomas.schuehly@outlook.com
github_username:  https://github.com/Thaiminater
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
